version: '3.3'

services:
  blog-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: api-go-blog
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: ./MySQL.Dockerfile
    image: mysql-go-blog
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./blog.sql:/docker-entrypoint-initdb.d/blog.sql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"